# apiVersion: v1
# kind: Secret
# metadata:
#   name: sync-blocked-email-domains
#   namespace: "mastodon"
#   labels:
#     app.kubernetes.io/name: sync-blocked-email-domains
#     app.kubernetes.io/instance: mastodon
# type: Opaque
# data:
#   key: ""
